export interface SellerSalesDc {
    monthactiveRetailer: number,
    monthtotalsale: any,
    monthtotalOrder: any,
    monthtotalLineitem: number,
    monthAvgOrderValue: any,
    monthAvgLineItem: any,
    TodayactiveRetailer: number,
    todaytotalsale: any,
    todaytotalOrder: number,
    todayAvgOrderValue: any,
    todaytotalLineitem: any,
    todayAvgLineItem: any,
    YesterdayactiveRetailer: number,
    Yesterdaytotalsale: any,
    YesterdaytotalOrder: number,
    YesterdayAvgOrderValue: any,
    YesterdaytotalLineitem: any,
    YesterdayAvgLineItem: any,
}
